version: '3.1'

services:
  
  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
  
  beacon-client:
    build: ./beacon-client-side
    depends_on:
      - selenium
